# config.yaml
agent_type: gemini # gpt-4o or qwen2.5-vl

gpt-4o:
  endpoint: https://xxx.openai.azure.com
  api_key: xxx
  api_version: 2025-xx-xx
  model_name: yfb-gpt-4o

qwen:
  endpoint: https://dashscope.aliyuncs.com/compatible-mode/v1
  api_key: your_api_key
  api_version: null
  model_name: qwen-plus
  vlm_model_name: qwen-vl-max

gemini:
  endpoint: https://generativelanguage.googleapis.com/v1beta
  api_key:your_api_key
  model_name: gemini-2.0-flash-exp
